name: npm Package Pull Request Commit Checks

on:
  workflow_call:
    secrets:
      FONTAWESOME_REGISTRY_AUTH_TOKEN:
        required: true

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup pnpm cache dir
        run: |
          PNPM_STORE_PATH="$( pnpm store path --silent )"
          if [ ! -d "$PNPM_STORE_PATH" ]; then
            mkdir -p "$PNPM_STORE_PATH"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "lts/*"
          cache: "pnpm"

      - name: Prepare Dependency Registries
        run: |
          echo "@fortawesome:registry = https://npm.fontawesome.com/" >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_REGISTRY_AUTH_TOKEN }}" >> .npmrc

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pre-Commitlint-specific scripts
        run: pnpm run --if-present "/^ci:pr:commitlint:pre:.*/"

      - name: Run Commitlint
        run: pnpm run "/^ci:pr:commitlint:main:.*/" -- --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run post-Commitlint-specific scripts
        run: pnpm run --if-present "/^ci:pr:commitlint:post:.*/"
